Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE

- src/main/java/com/palpal/dealightbe/domain/address/domain/Address.java
- src/main/java/com/palpal/dealightbe/domain/member/domain/Member.java
- src/main/java/com/palpal/dealightbe/domain/oAuth/domain/OAuth.java
- src/main/java/com/palpal/dealightbe/domain/order/domain/OrderStatus.java
- src/main/java/com/palpal/dealightbe/domain/store/domain/Store.java
- close: #7
어떤 변경 사항이 있나요?
- 엔티티 패키지명 수정
> feat : entity 수정 #7

- README.md
> docs: update README.md

- src/main/java/com/palpal/dealightbe/global/error/GlobalExceptionHandler.java
- close: #29 
어떤 변경 사항이 있나요?
- GlobalExceptionHandler에 누락된 예외 추가
> hotfix: GlobalExceptionHandler에 누락된 예외 추가

- build.gradle
> branch내 시큐리티 관련 주석 처리

- src/docs/asciidoc/item.adoc
- src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
- src/main/java/com/palpal/dealightbe/domain/item/application/dto/request/ItemReq.java
- src/main/java/com/palpal/dealightbe/domain/item/application/dto/response/ItemRes.java
- src/main/java/com/palpal/dealightbe/domain/item/domain/Item.java
- src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepository.java
- src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
- src/main/java/com/palpal/dealightbe/domain/store/domain/StoreRepository.java
- src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
- src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
- close: #9 
어떤 변경 사항이 있나요?
- 상품 등록 API 구현
- 상품 등록 테스트 코드 작성
- 상품 등록 RestDocs 작성
- 상품 등록 기능을 구현했습니다.
- 상품 이미지 같은 경우엔 나중에 추가할 예정이라 null로 입력하도록 했습니다!
- 상품 테스트 코드와 RescDocs를 작성했습니다.
- 수정해야 할 부분이 있다면 코멘트 부탁드립니다!
> 상품 등록 API 구현

- build.gradle
- src/main/java/com/palpal/dealightbe/config/S3Config.java
- src/main/java/com/palpal/dealightbe/domain/image/ImageService.java
- src/main/java/com/palpal/dealightbe/domain/image/exception/ImageIOException.java
- src/main/java/com/palpal/dealightbe/domain/image/exception/InvalidFileTypeException.java
- src/main/java/com/palpal/dealightbe/domain/image/infrastructure/S3ImageService.java
- src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
- close: https://github.com/Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE/issues/37
어떤 변경 사항이 있나요?
- 이미지 업로드 및 삭제를 위한 S3ImageService를 추가하고자 이미지 관련 도메인을 새로 추가했습니다. ImageService 인터페이스를 통해 이미지 관련 작업을 수행할 수 있습니다.
- ImageService 인터페이스를 추가했습니다.
- ImageService를 구현한 S3ImageService를 추가했습니다.
- 현재 application-aws.yml은 따로 업로드 하지 않았습니다!
> 이미지 도메인 생성

- src/docs/asciidoc/Store.adoc
- src/main/java/com/palpal/dealightbe/domain/member/domain/Member.java
- src/main/java/com/palpal/dealightbe/domain/member/domain/MemberRole.java
- src/main/java/com/palpal/dealightbe/domain/member/domain/Role.java
- src/main/java/com/palpal/dealightbe/domain/member/domain/RoleType.java
- src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
- src/main/java/com/palpal/dealightbe/domain/store/application/dto/response/StoreInfoRes.java
- src/main/java/com/palpal/dealightbe/domain/store/domain/Store.java
- src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
- src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
- src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
- close: #23 
어떤 변경 사항이 있나요?
- 업체 입장에서 본인의 마이 페이지를 조회하는 API를 구현하였습니다.
- 조회시 업체 소유자와 요청자가 같지 않으면 예외를 던져주는 식으로 구현했습니다.
- 등록 API와 마찬가지로 토큰 관련 AOP가 완성되면 path parameter의 memberId는 없어질 예정입니다!
빠진 부분이나 유효성 검사등 코드 레벨에서 봐주시면 감사하겠습니다!
---
> 업체 마이페이지 조회 API 및 RestDocs 구현

- src/docs/asciidoc/Item.adoc
- src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
- src/main/java/com/palpal/dealightbe/domain/item/domain/Item.java
- src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
- src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
- close: #13 
어떤 변경 사항이 있나요?
- 상품 수정 API 구현
- 상품 수정 테스트 코드 작성
- 상품 수정 RestDocs 작성
- 상품 수정 기능을 구현했습니다.
- 상품 테스트 코드와 RestDocs를 작성했습니다.
> 상품 수정 API 구현

- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
- src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
- src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
- close: #
어떤 변경 사항이 있나요?
- Controller 테스트 코드들이 시큐리티 적용 후 통과시키기 위해 excludeAutoConfiguration 설정을 추가했습니다.
> hotfix: Controller 테스트 코드 excludeAutoConfiguration 설정 추가

- src/docs/asciidoc/Store.adoc
- src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
- src/main/java/com/palpal/dealightbe/domain/store/application/dto/request/StoreUpdateReq.java
- src/main/java/com/palpal/dealightbe/domain/store/application/dto/response/StoreUpdateRes.java
- src/main/java/com/palpal/dealightbe/domain/store/domain/Store.java
- src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
- src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
- close: #27 
어떤 변경 사항이 있나요?
- 업체 마이페이지에서 정보를 수정할 수 있는 API를 작성하였습니다.
- 업체에서 마이페이지에서 수정 가능한 정보들을 수정할 수 있습니다.
- 업체 전화 번호
- 업체 주소(에 따른 X,Y좌표)
- 영업 시간(오픈/마감)
- 휴무일
> 업체 마이페이지 정보 수정 API 및 RestDocs 

- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
- src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
- src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
> hotfix: controller 테스트 코드에 OAuth2ClientAutoConfiguration.class 제외

- src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
> hotfix: ItemControllerTest, ItemServiceTest 테스트 코드 수정

- src/docs/asciidoc/Item.adoc
- src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
- src/main/java/com/palpal/dealightbe/domain/item/domain/Item.java
- src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepository.java
- src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
- src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
- src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
- src/test/java/com/palpal/dealightbe/domain/order/presentation/OrderControllerTest.java
- close: #14 
어떤 변경 사항이 있나요?
- 상품 삭제 API 구현
- 상품 삭제 테스트 코드 작성
- 상품 삭제 RestDocs 작성
- 상품 삭제 기능을 구현했습니다.
- 상품 테스트 코드와 RestDocs를 작성했습니다.
> 상품 삭제 API 구현

- src/main/java/com/palpal/dealightbe/domain/member/application/MemberService.java
- close: #67 
어떤 변경 사항이 있나요?
- MemberService 클래스 단에 @Transactional 애너테이션이 2개가 붙어 오류가 발생하여 1개만 남겨두었습니다.
> hotfix: MemberService 애너테이션 수정

- src/docs/asciidoc/Store.adoc
- src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
- src/main/java/com/palpal/dealightbe/domain/store/application/dto/request/StoreCreateReq.java
- src/main/java/com/palpal/dealightbe/domain/store/application/dto/request/StoreStatusReq.java
- src/main/java/com/palpal/dealightbe/domain/store/application/dto/response/StoreStatusUpdateRes.java
- src/main/java/com/palpal/dealightbe/domain/store/domain/Store.java
- src/main/java/com/palpal/dealightbe/domain/store/domain/StoreStatus.java
- src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
- src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
- src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
- close: #25 
어떤 변경 사항이 있나요?
- 홈 화면에서 버튼을 눌러 가게 영업 상태를 변경할 수 있는 API를 작성하였습니다.
- Body값에 영업 유무 값을 받아 변경할 수 있도록 하였습니다.
---
> 가게 영업 상태 변경 API 

- src/docs/asciidoc/Item.adoc
> hotfix: Item.adoc 내용 수정

- src/docs/asciidoc/Item.adoc
- src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
- src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepository.java
- src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
- src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
- close: #16 
어떤 변경 사항이 있나요?
- 상품 상세 정보 조회(단건) API 구현
- 상품 상세 정보 조회(단건) 테스트 코드 작성
- 상품 상세 정보 조회(단건) RestDocs 작성
- 상품 상세 정보 조회(단건) 기능을 구현했습니다.
- 테스트 코드와 RestDocs를 작성했습니다.
> 상품 상세 정보 조회(단건) API 구현

- src/docs/asciidoc/Store.adoc
- src/main/java/com/palpal/dealightbe/domain/image/application/dto/request/ImageUploadReq.java
- src/main/java/com/palpal/dealightbe/domain/image/application/dto/response/ImageRes.java
- src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
- src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
- src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
- close: #60 
어떤 변경 사항이 있나요?
- 업체 이미지 등록 API 입니다.
- 업체 등록시 기본으로 등록되는 디폴트 이미지는 아직 구현되지 않았으며, 새로 이슈를 파서 작업할 생각입니다.
---
> 업체 이미지 등록 API

- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
- src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
- src/test/java/com/palpal/dealightbe/domain/order/presentation/OrderControllerTest.java
- src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
> Rest Docs 빌드 경로 수정

- src/docs/asciidoc/member.adoc
- src/main/java/com/palpal/dealightbe/domain/address/application/dto/request/AddressReq.java
- src/main/java/com/palpal/dealightbe/domain/address/domain/Address.java
- src/main/java/com/palpal/dealightbe/domain/image/dto/request/ImageUploadReq.java
- src/main/java/com/palpal/dealightbe/domain/image/dto/response/ImageRes.java
- src/main/java/com/palpal/dealightbe/domain/member/application/MemberService.java
- src/main/java/com/palpal/dealightbe/domain/member/application/dto/request/MemberUpdateReq.java
- src/main/java/com/palpal/dealightbe/domain/member/domain/Member.java
- src/main/java/com/palpal/dealightbe/domain/member/presentation/MemberController.java
- src/test/java/com/palpal/dealightbe/domain/member/application/MemberServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
- close: https://github.com/Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE/issues/20
어떤 변경 사항이 있나요?
- 고객 프로필 이미지 수정 API를 작성했습니다.
- 고객 프로필 이미지 수정 API를 작성했습니다.
- RestDocs를 활용하여 API 엔드포인트 문서화 작업을 했습니다.
> 고객 프로필 이미지 수정 API

- src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
- close: #
어떤 변경 사항이 있나요?
- Member 컨트롤러 테스트 내 import 문 수정
> hotfix: Member 컨트롤러 테스트 내 import 문 수정

- src/docs/asciidoc/Store.adoc
- src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
- src/main/java/com/palpal/dealightbe/domain/store/application/dto/response/StoreStatusRes.java
- src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
- src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
- close: #75 
어떤 변경 사항이 있나요?
- 업체의 영업 상태를 조회하는 API를 구현하였습니다.
- 단순한 조회 로직 입니다!
> 업체 영업 상태 조회 API

- src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
- src/main/java/com/palpal/dealightbe/domain/store/application/dto/request/StoreCreateReq.java
- src/main/java/com/palpal/dealightbe/domain/store/application/dto/response/StoreCreateRes.java
- src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
- close: #74 
어떤 변경 사항이 있나요?
- 업체 등록시 기본 이미지 등록되게 변경
- 업체 등록시 Response 필드에 업체 ID 추가
- 업체 등록시 S3에 등록되어 있는 업체 기본 이미지가 등록되게 해두었습니다.
- 프론트 쪽의 요청으로 업체 등록 후 응답 필드에 Long 타입으로 업체 Id를 추가했습니다.
> 업체 등록시 기본 이미지 등록

- src/docs/asciidoc/Item.adoc
- src/main/java/com/palpal/dealightbe/config/JpaConfig.java
- src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
- src/main/java/com/palpal/dealightbe/domain/item/application/dto/response/ItemsRes.java
- src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepository.java
- src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepositoryCustom.java
- src/main/java/com/palpal/dealightbe/domain/item/infrastructure/ItemRepositoryImpl.java
- src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
- src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
- close: #71 
어떤 변경 사항이 있나요?
- 상품 목록 조회(업체 시점) API 구현
- 상품 목록 조회  테스트 코드 작성
- 상품 목록 조회 RestDocs 작성
- 업체 홈 화면에 해당하는 상품 목록 조회 API 구현을 구현했습니다.
- 테스트 코드와 RestDocs를 작성했습니다.
> 상품 목록 조회(업체 시점) API 구현

- src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
> hotfix: ItemServiceTest itemFindAllForStoreSuccessTest 메서드 수정

- src/docs/asciidoc/Store.adoc
- src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
- src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
- src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
- close: #62 
어떤 변경 사항이 있나요?
- 업체 이미지 수정 가능한 API 구현
- 업체가 이미지 수정을 요청하면 기존의 있던 이미지는 S3에서 삭제하고, 요청한 새로운 이미지를 S3에 저장합니다.
---
> 업체 이미지 수정 API

- src/docs/asciidoc/Item.adoc
- src/docs/asciidoc/Order.adoc
- src/main/java/com/palpal/dealightbe/domain/order/application/OrderService.java
- src/main/java/com/palpal/dealightbe/domain/order/application/dto/response/OrdersRes.java
- src/main/java/com/palpal/dealightbe/domain/order/domain/Order.java
- src/main/java/com/palpal/dealightbe/domain/order/domain/OrderRepository.java
- src/main/java/com/palpal/dealightbe/domain/order/presentation/OrderController.java
- src/main/java/com/palpal/dealightbe/domain/store/domain/Store.java
- src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
- src/test/java/com/palpal/dealightbe/domain/order/application/OrderServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/order/domain/OrderRepositoryTest.java
- src/test/java/com/palpal/dealightbe/domain/order/presentation/OrderControllerTest.java
- src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
- close: #19, #22
어떤 변경 사항이 있나요?
request에서 query parameter는 필수인지 여부를 나타내는 칼럼(required) 추가했습니다
> 주문 목록 조회 - 업체&고객

- src/test/java/com/palpal/dealightbe/domain/order/application/OrderServiceTest.java
> hotfix : test 코드 수정

- src/docs/asciidoc/Store.adoc
- src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
- close: #105 
어떤 변경 사항이 있나요?
- AOP 적용 후 변동 사항을 서비스 테스트 레이어에 적용하지 않아 발생한 오류 수정입니다.
> 업체 서비스 테스트 코드 변경 사항 반영

- src/main/java/com/palpal/dealightbe/domain/order/application/OrderService.java
- src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
- src/test/java/com/palpal/dealightbe/domain/order/application/OrderServiceIntegrationTest.java
- src/test/java/com/palpal/dealightbe/domain/order/application/OrderServiceTest.java
> 주문 생성 테스트 코드 추가

- src/docs/asciidoc/Store.adoc
- src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
- src/main/java/com/palpal/dealightbe/domain/store/application/dto/response/StoreByMemberRes.java
- src/main/java/com/palpal/dealightbe/domain/store/domain/StoreRepository.java
- src/main/java/com/palpal/dealightbe/domain/store/presentation/StoreController.java
- src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
- close: #102 
어떤 변경 사항이 있나요?
- 회원가입(로그인)한 유저의 토큰을 이용하여 등록한 업체가 있는지 조회
- 프론트쪽에서 응답을 Json 형식으로 원하여 DTO객체로 한번 감쌌습니다
---
> 회원가입 완료 고객의 업체 등록 유무 확인 API

- src/docs/asciidoc/Item.adoc
- src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
- src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
- src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
- close: #117 
어떤 변경 사항이 있나요?
- 상품 이미지 수정 기능 추가
> 상품 이미지 수정 기능

- src/docs/asciidoc/Item.adoc
- src/main/java/com/palpal/dealightbe/config/JpaConfig.java
- src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
- close: #123 
어떤 변경 사항이 있나요?
- 상품 삭제 시 상품 이미지도 함께 삭제하는 기능을 추가했습니다.
- Rest Docs를 수정했습니다.
> 상품 이미지 삭제 기능

- src/main/java/com/palpal/dealightbe/config/JpaConfig.java
- src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
- close: #129 
어떤 변경 사항이 있나요?
- 상품 목록 조회 시 페이지 번호가 1부터 시작하도록 설정했습니다.
> hotfix: 상품 목록 조회 시 페이지 번호 수정

- src/docs/asciidoc/Item.adoc
- src/main/java/com/palpal/dealightbe/domain/item/application/dto/response/ItemRes.java
- src/main/java/com/palpal/dealightbe/domain/item/application/dto/response/ItemsRes.java
- src/main/resources/static/docs/Item.html
- src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
- close: #131 
어떤 변경 사항이 있나요?
- 상품 관련 response dto 수정
- 테스트코드, 명세 수정
> hotfix: 상품 Response Dto 리팩토링

- src/main/java/com/palpal/dealightbe/domain/member/application/MemberService.java
- src/main/java/com/palpal/dealightbe/domain/member/domain/MemberRole.java
- src/main/java/com/palpal/dealightbe/domain/member/presentation/MemberController.java
- src/test/java/com/palpal/dealightbe/domain/member/application/MemberServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
- close: https://github.com/Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE/issues/118
어떤 변경 사항이 있나요?
- 멤버 도메인 내 인증을 위해 컨트롤러에 @providerId를 적용했습니다.
- 멤버 컨트롤러 내 인증을 위한 @providerId를 적용하고, 그에 따라 테스트 코드를 수정했습니다.
> 인증 관련 AOP 적용(멤버)

- src/main/java/com/palpal/dealightbe/domain/order/presentation/OrderController.java
- close: #142
어떤 변경 사항이 있나요?
아래 요청 사항에 대한 수정입니다
> 페이징 - 페이지 1부터 시작하도록 수정

- .github/workflows/script-for-test.yml
- src/main/java/com/palpal/dealightbe/config/SecurityConfig.java
- src/main/java/com/palpal/dealightbe/domain/auth/presentation/CustomOAuth2AuthenticationSuccessHandler.java
- src/main/java/com/palpal/dealightbe/domain/image/infrastructure/S3ImageService.java
- close: #143 
어떤 변경 사항이 있나요?
배포서버에서 카카오 로그인 이후 Redirect URL 접근시 404 에러가 뜨는 오류를 해결했습니다.
배포서버에서 카카오 로그인 이후 Redirect URL 접근시 404 에러가 뜨는 오류를 해결했는데,,,
그냥 제가 세팅 값을 잘 못 집어넣어서 생긴 문제였네요... ㅠㅠ 저희 코드가 바뀌는 부분도 없었고
Actions에 있는 Secret에서 DEV_OAUTH.YML에서 값을 변경하는 것으로 해결됐습니다..!
따로 코드 확인하실 필요는 없을거 같아요~
> 배포서버에서 카카오 로그인 이후 Redirect URL 접근시 404 에러가 뜨는 오류

- .github/workflows/script-dev.yml
- .github/workflows/script-test-144.yml
- build.gradle
- scripts/deploy.sh
- src/main/java/com/palpal/dealightbe/config/SecurityConfig.java
- close: #144
어떤 변경 사항이 있나요?
[https://server.dealight.store/docs](https://server.dealight.store/docs)에 접속하면
NGINX에 의해 REST Docs 파일을 조회할 수 있도록 세팅을 진행했습니다.
페이지에 편하게 접근할 수 있도록 index.html 파일을 만들었습니다.(배포서버에만 있는 파일)
CI/CD를 진행할 때 REST Docs가 업데이트 되면 문서가 최신화되도록
배포스크립트들을 변경했습니다.
서비스 코드에서 바뀐 부분은 없고 배포스크립트만 변경되었습니다.
나머지 변경 사항은 개발서버에서 진행되었습니다.
> 배포환경에서 NGINX를 통해 RestDocs 파일에 접근하도록 변경

- src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
- src/main/java/com/palpal/dealightbe/domain/item/application/dto/response/ItemsRes.java
- src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepository.java
- src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepositoryCustom.java
- src/main/java/com/palpal/dealightbe/domain/item/infrastructure/ItemRepositoryImpl.java
- src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
- close: #163 
어떤 변경 사항이 있나요?
- 상품 목록 페이징 Slice 처리
> 상품 목록 페이징 Slice 처리

- src/docs/asciidoc/Store.adoc
- src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
- src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/store/domain/StoreRepositoryTest.java
- src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
- close: #161 
어떤 변경 사항이 있나요?
- 업체 검색 컨트롤러 테스트
- RestDocs 작성
> 업체 검색 컨트롤러 테스트 및 RestDocs

- src/docs/asciidoc/Cart.adoc
- src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
- src/main/java/com/palpal/dealightbe/domain/cart/application/dto/response/CartsRes.java
- src/main/java/com/palpal/dealightbe/domain/cart/domain/Cart.java
- src/main/java/com/palpal/dealightbe/domain/cart/domain/CartAdditionType.java
- src/main/java/com/palpal/dealightbe/domain/cart/presentation/CartController.java
- src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
- src/main/resources/static/docs/Cart.html
- src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
- close: #138 
어떤 변경 사항이 있나요?
- 장바구니 조회 API 구현
- 테스트 코드, REST DOCS 작성
- 장바구니 담기 API 코드 리팩토링
- 장바구니 조회 API를 구현했습니다.
- 2가지의 장바구니 담기 API를 리팩토링하여 1개의 API로 합쳤습니다.
> 장바구니 조회 API 구현

- src/docs/asciidoc/Cart.adoc
- src/docs/asciidoc/Item.adoc
- src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
- src/main/java/com/palpal/dealightbe/domain/cart/application/dto/request/CartsReq.java
- src/main/java/com/palpal/dealightbe/domain/cart/application/dto/response/CartRes.java
- src/main/java/com/palpal/dealightbe/domain/cart/domain/Cart.java
- src/main/java/com/palpal/dealightbe/domain/cart/presentation/CartController.java
- src/main/java/com/palpal/dealightbe/domain/item/application/ItemService.java
- src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
- src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
- src/main/java/com/palpal/dealightbe/global/ListSortType.java
- src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
- src/main/resources/static/docs/Cart.html
- src/main/resources/static/docs/Item.html
- src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
- close: #165 
어떤 변경 사항이 있나요?
- 장바구니 만료 방식 변경
- 장바구니 수정 API 구현
- 장바구니 수정 API 테스트 코드, Rest Docs 작성
- 장바구니 만료 방식을 변경했습니다.
- 기존에 영업 시간까지의 남은 시간 (초단위)를 등록한 다음, 남은 시간이 모두 소멸되면 장바구니에 담긴 상품을 삭제하는 방식으로 구현했었으나, 업체 업데이트 최신화 문제로 장바구니 조회할 때 장바구니를 최신화 하여 만료된 상품들을 삭제하는 방식으로 변경했습니다.
- 장바구니 수정 API를 구현했습니다.
- 장바구니 수정 API 테스트 코드와, Rest Docs를 작성했습니다.
> 장바구니 수정 API 구현

- src/docs/asciidoc/Order.adoc
- src/docs/asciidoc/Review.adoc
- src/main/java/com/palpal/dealightbe/domain/order/application/OrderService.java
- src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
- src/test/java/com/palpal/dealightbe/domain/order/application/OrderServiceIntegrationTest.java
- src/test/java/com/palpal/dealightbe/domain/order/domain/OrderRepositoryTest.java
- src/test/java/com/palpal/dealightbe/domain/order/presentation/OrderControllerTest.java
- src/test/java/com/palpal/dealightbe/domain/review/presentation/ReviewControllerTest.java
- close: #172
어떤 변경 사항이 있나요?
- rest docs에 요청 실패하는 경우 추가
- 업체가 영업 종료된 경우 검증 추가
> rest docs - 실패 테스트 추가(주문/리뷰)

- src/docs/asciidoc/Cart.adoc
- src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
- src/main/java/com/palpal/dealightbe/domain/cart/presentation/CartController.java
- src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
- src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
- close: #168
어떤 변경 사항이 있나요?
- 장바구니 삭제 API 구현
- 장바구니 삭제 API를 구현했습니다.
- 장바구니 삭제 API 테스트 코드, Rest Docs를 작성했습니다.
> 장바구니 삭제 API 구현

- src/main/java/com/palpal/dealightbe/domain/cart/domain/Cart.java
- src/main/java/com/palpal/dealightbe/domain/item/domain/Item.java
- src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepository.java
- src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
- src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
- src/test/java/com/palpal/dealightbe/domain/item/application/ItemServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
- close: #176 
어떤 변경 사항이 있나요?
- 업체 영업 종료 시 상품 삭제 기능 추가
- 업체가 영업을 종료했을 때 등록한 상품들을 삭제하는 기능을 추가했습니다.
> 업체 영업 종료 시 상품 삭제 기능 추가

- src/main/java/com/palpal/dealightbe/domain/member/application/dto/response/MemberProfileRes.java
- src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
- close: https://github.com/Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE/issues/181
어떤 변경 사항이 있나요?
- 멤버 프로필 조회시 반환되는 데이터를 수정했습니다.
- MemberProfileRes에 providerId, role 추가
- MemberControllerTest 수정
> Member 프로필 조회 수정

- src/docs/asciidoc/Item.adoc
- close: #184 
어떤 변경 사항이 있나요?
- Item 명세를 수정했습니다.
> hotfix: Item.adoc 수정

- src/test/java/com/palpal/dealightbe/domain/member/application/MemberServiceTest.java
- close: 
어떤 변경 사항이 있나요?
- MemberServiceTest 내 프로필 조회 테스트 코드를 수정했습니다.
- 기존의 Member 프로필 조회 관련 코드가 변경되었으나 서비스 테스트 코드에 반영이 되어 있지 않아 테스트 코드가 실패하는 문제가 발생해, 테스트 코드를 수정했습니다.
> hotfix: MemberServiceTest 수정

- src/docs/asciidoc/Cart.adoc
- src/docs/asciidoc/Item.adoc
- src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
- close: #187 
어떤 변경 사항이 있나요?
- Item(상품), Cart(장바구니) 명세를 수정했습니다.
> hotfix: Item, Cart 명세 수정

- src/main/java/com/palpal/dealightbe/domain/member/application/dto/response/MemberProfileRes.java
- close: 
어떤 변경 사항이 있나요?
- Member프로필 반환 DTO 내 필드 수정를 수정했습니다.
- Member 프로필 반환 DTO 내에서 ROLE객체가 반환되는 부분을 수정했습니다.
> hotfix: Member 프로필 반환 DTO 필드 수정

- src/docs/asciidoc/Cart.adoc
- src/docs/asciidoc/Item.adoc
- src/main/java/com/palpal/dealightbe/domain/item/infrastructure/ItemRepositoryImpl.java
- src/test/java/com/palpal/dealightbe/domain/item/domain/ItemRepositoryTest.java
- close: #179 
어떤 변경 사항이 있나요?
- ItemRepositoryTest 작성
- Item, Cart 명세 수정
- ItemRepositoryTest를 작성했습니다.
- Item, Cart 명세를 수정했습니다.
> ItemRepositoryTest 작성

- src/test/java/com/palpal/dealightbe/domain/item/domain/ItemRepositoryTest.java
- close: #199 
어떤 변경 사항이 있나요?
- ItemRepositoryTest 테스트 코드 수정
> hotfix: ItemRepositoryTest 테스트 코드 수정

- src/docs/asciidoc/Member.adoc
- src/main/java/com/palpal/dealightbe/domain/member/application/dto/response/MemberProfileRes.java
- src/main/resources/static/docs/Member.html
- src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
- close: #
어떤 변경 사항이 있나요?
- Member 프로필 반환 DTO 필드 수정 및 Member.adoc 파일을 수정했습니다.
- Member 프로필 반환 DTO 필드 중 Role과 관련해 name이 아닌 role을 반환하도록 수정
- Member.adoc 내 불필요한 구문들 삭제
> hotfix: Member 프로필 반환 DTO 필드 수정 및 Member.adoc 수정

- src/docs/asciidoc/Item.adoc
- src/main/java/com/palpal/dealightbe/domain/item/presentation/ItemController.java
- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
- close: #202 
어떤 변경 사항이 있나요?
- 향후 페이징 기능 성능 개선(no offset) 처리를 위해 엔드포인트를 미리 수정했습니다.
> ItemController 목록 조회 기능 엔드 포인트 수정

- src/docs/asciidoc/Review.adoc
> docs : Review.adoc 형식 수정

- src/test/java/com/palpal/dealightbe/domain/review/presentation/ReviewControllerTest.java
> test : ReviewControllerTest 에서 예외에 대한 명세 수정

- src/docs/asciidoc/Order.adoc
- src/docs/asciidoc/Review.adoc
- src/test/java/com/palpal/dealightbe/domain/review/presentation/ReviewControllerTest.java
> docs : 명세 형식 및 오타 수정

- src/test/java/com/palpal/dealightbe/domain/review/presentation/ReviewControllerTest.java
> hotfix : 테스트 내의 mocking 오류 수정

- src/docs/asciidoc/Store.adoc
- src/main/java/com/palpal/dealightbe/domain/store/application/StoreService.java
- src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
- src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
- close: #198 
어떤 변경 사항이 있나요?
- 업체 등록시 해당 고객이 이미 업체를 보유하고 있는지 체크하는 검증 로직 구현
- 기존에 중복으로 업체를 등록할 수 있었던 버그를 수정하였습니다.
> 업체 등록시 이미 업체를 보유하고 있는지 유효성 검사 추가

- build.gradle
- src/main/java/com/palpal/dealightbe/domain/auth/domain/Jwt.java
- src/main/java/com/palpal/dealightbe/domain/auth/filter/JwtAuthenticationFilter.java
- src/main/java/com/palpal/dealightbe/domain/auth/presentation/AuthController.java
- src/main/resources/application-actuator.yml
- src/main/resources/application.yml
- src/test/java/com/palpal/dealightbe/domain/auth/presentation/AuthControllerTest.java
- close: #146 
어떤 변경 사항이 있나요?
액추에이터, 프로메테우스, 그라파나 설정 관련 파일을 추가했습니다.
로컬에서 연결이 되는 건 확인했고, 도커 컴포즈는 EC2에서 모든 설정을 테스트해본 뒤 작성할 예정입니다.
> 스프링 액츄에이터, 메트릭, 프로메테우스, 그라파나 도입

- src/main/java/com/palpal/dealightbe/domain/member/domain/Member.java
어떤 변경 사항이 있나요?
- 현재 Member 프로필 수정 기능과 관련해 오류가 발생해 해당 부분을 수정했습니다.
- Member 프로필 주소 업데이트 로직을 수정했습니다.
> hotfix: Member 프로필 주소 업데이트 로직 수정

- src/main/java/com/palpal/dealightbe/domain/store/domain/StoreRepositoryImpl.java
- close: #222 
어떤 변경 사항이 있나요?
- 업체 검색시 모든 정렬 조건에 불필요한 거리 (3km이내 -> 이미 where절에서 필터링 해줌)를 기준으로 정렬하는 것이 있었습니다. 해당 부분 제거 하였습니다.
> 업체 검색 QueryDSL 불필요한 정렬 조건 삭제

- src/main/java/com/palpal/dealightbe/domain/store/application/dto/response/StoreCreateRes.java
- src/main/java/com/palpal/dealightbe/domain/store/application/dto/response/StoreInfoRes.java
- src/test/java/com/palpal/dealightbe/domain/store/application/StoreServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/store/presentation/StoreControllerTest.java
- close: #141 
어떤 변경 사항이 있나요?
- 업체 마이페이지 조회시 DayOffs필드 관련 LazyLoading 문제가 생겼습니다.
- 관련하여 Set<DayOff> -> Set<String> 으로 바꾼 후 Stream사용하여 변환해주었습니다.
> DayOffs 필드 LazyLoading 수정

- src/main/resources/application.yml
- src/main/resources/console-appender.xml
- src/main/resources/error-appender.xml
- src/main/resources/info-appender.xml
- src/main/resources/logback.xml
- src/main/resources/warn-appender.xml
> 로깅 세팅 + ddl-auto update로 변경

- src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
- close: #236 
어떤 변경 사항이 있나요?
-  장바구니 수정 기능 최신화 로직 추가
- 장바구니 수정 시 장바구니에 담긴 상품들 상태를 최신화 하고 수정하는 기능을 추가했습니다.
> hotfix: 장바구니 수정 기능 최신화 로직 추가

- src/main/java/com/palpal/dealightbe/domain/order/domain/Order.java
> feat : 주문 다건 조회 버그 수정

- src/docs/asciidoc/Cart.adoc
- src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
- src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
- close: #238 
어떤 변경 사항이 있나요?
- 장바구니 담기 기능 최신화 로직 추가
- 장바구니 담기 기능에 상품 상태를 최신화 하는 로직을 추가했습니다.
- 이 과정에서 나타날 수 있는 예외 상황(담기 실패)에 대한 Controller 테스트와 명세를 추가로 작성했습니다.
> hotfix: 장바구니 담기 기능 최신화 로직 추가

- src/docs/asciidoc/Review.adoc
- src/main/java/com/palpal/dealightbe/domain/order/domain/Order.java
- src/main/java/com/palpal/dealightbe/domain/review/application/ReviewService.java
- src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
- src/test/java/com/palpal/dealightbe/domain/review/application/ReviewServiceIntegrationTest.java
- src/test/java/com/palpal/dealightbe/domain/review/presentation/ReviewControllerTest.java
> 리뷰 API 버그 수정

- src/main/java/com/palpal/dealightbe/domain/item/domain/Item.java
- src/main/java/com/palpal/dealightbe/domain/order/application/OrderService.java
- src/test/java/com/palpal/dealightbe/domain/order/application/OrderServiceIntegrationTest.java
> 주문 취소시 재고 증가

- src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
- close: #249
어떤 변경 사항이 있나요?
- CartService 중복 코드 제거
> hotfix: CartService 중복 코드 제거

- .github/workflows/script-dev.yml
- .github/workflows/script-test.yml
- .github/workflows/sonarcloud.yml
- appspec.yml
- docker-compose.infra.yml
- scripts/afterDeploy.sh
- scripts/beforeDeploy.sh
- scripts/deploy.sh
- scripts/infra.sh
- src/docs/asciidoc/Auth.adoc
- src/main/java/com/palpal/dealightbe/domain/member/application/MemberService.java
- src/main/resources/error-appender.xml
- src/main/resources/info-appender.xml
- src/main/resources/warn-appender.xml
- close: #192 
어떤 변경 사항이 있나요?
무중단 배포에 필요한 EC2 추가설정, 도커 컴포즈 구성 및 컨테이너 볼륨 추가, 네트워크 구성으로 고도화
> 무중단 배포에 필요한 EC2 추가설정, 도커 컴포즈 구성 및 컨테이너 볼륨 추가, 네트워크 구성으로 고도화

- src/main/java/com/palpal/dealightbe/DealightBeApplication.java
- src/main/java/com/palpal/dealightbe/config/SchedulerConfig.java
- src/main/java/com/palpal/dealightbe/domain/notification/application/NotificationService.java
- src/main/java/com/palpal/dealightbe/domain/notification/domain/Notification.java
- src/main/java/com/palpal/dealightbe/domain/notification/domain/NotificationRepository.java
- src/main/java/com/palpal/dealightbe/domain/order/application/OrderService.java
- close: https://github.com/Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE/issues/229
어떤 변경 사항이 있나요?
- 읽은 알림 일괄 삭제를 위한 스케줄링을 적용했습니다.
- 읽은 알림 처리를 위한 스케줄링을 적용했습니다. 매주 화요일 새벽 2시에 진행하도록 설정했습니다.
- 기본 스케줄러가 단일 스레드로 동작하기에, SchedulingConfigurer 인터페이스를 통해 스레드 풀의 크기를 10으로 조절했습니다.
> SSE 알림 스케줄링 적용

- src/main/java/com/palpal/dealightbe/domain/review/application/dto/request/ReviewCreateReq.java
- src/test/java/com/palpal/dealightbe/domain/review/application/ReviewServiceIntegrationTest.java
- close: #244
어떤 변경 사항이 있나요?
리뷰 작성시 중복이 있어도 정상작동.
단, DB에는 중복을 제거한 데이터만 저장.
> 리뷰 작성 API - 중복 있는 경우

- src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
- close: #254
어떤 변경 사항이 있나요?
- 업체가 영업을 종료했을 경우 장바구니 상품이 만료되어 삭제처리 하는 로직 추가
> 업체 영업 종료 시 장바구니 상품 만료 삭제 로직 추가

- src/docs/asciidoc/Cart.adoc
- src/docs/asciidoc/Item.adoc
- src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
- src/main/java/com/palpal/dealightbe/domain/cart/domain/CartRepository.java
- src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
- src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
- close: #256 
어떤 변경 사항이 있나요?
- 업체 변동 사항으로 나타날 수 있는 장바구니 기능 버그 수정
- 컨트롤러 테스트코드, 명세 추가 작성 (실패 케이스)
- 장바구니에 상품을 담은 상태에서, 업체가 해당 상품을 삭제하거나 업체 자체가 삭제되면 장바구니에 있는 조회, 담기, 수정 기능에 생기는 버그를 수정합니다. (업체에 변동사항 있을 시 장바구니에도 상황 반영)
> hotfix: 장바구니 기능 버그 수정

- src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
- close: #260
어떤 변경 사항이 있나요?
- CartService 코드 리팩토링
- CartService의 담기 메서드의 쿼리 중복 호출 메서드를 제거했습니다.
> hotfix: CartService 코드 리팩토링

- src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
- src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
> hotfix: 장바구니에서 0개의 수량은 담지 못하도록 수정

- src/main/java/com/palpal/dealightbe/domain/item/domain/Item.java
- src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
- src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
- src/test/java/com/palpal/dealightbe/domain/item/presentation/ItemControllerTest.java
- close: #273 
어떤 변경 사항이 있나요?
- 상품 할인가&원가 조건 수정
> hotfix: 상품 할인가&원가 조건 수정

- src/main/java/com/palpal/dealightbe/domain/member/domain/MemberRepository.java
- src/main/java/com/palpal/dealightbe/domain/notification/application/NotificationService.java
- src/main/java/com/palpal/dealightbe/domain/notification/application/dto/NotificationUserInfo.java
- src/main/java/com/palpal/dealightbe/domain/notification/application/dto/response/NotificationUserInfo.java
- src/main/java/com/palpal/dealightbe/domain/notification/application/dto/response/NotificationsRes.java
- src/main/java/com/palpal/dealightbe/domain/notification/domain/NotificationRepository.java
- src/main/java/com/palpal/dealightbe/domain/notification/presentation/NotificationController.java
- src/main/java/com/palpal/dealightbe/domain/order/application/OrderService.java
- close: https://github.com/Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE/issues/269
어떤 변경 사항이 있나요?
- SSE 알림 내 인증 AOP를 적용했습니다.
- 기존에 member, store별로 따로 두었던 알림 관련 엔드포인트들을, 인증 AOP를 적용하며 하나로 통합했습니다.
- 알림 조회시 무한 스크롤을 적용하기 위해 컨트롤러의 반환타입을 수정했습니다.
- Order 서비스 내 알림 발송 로직을 적용했습니다.
> SSE 알림 내 인증 AOP 적용

- src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
- src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
- src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
- close: #283 
어떤 변경 사항이 있나요?
- 장바구니 에러 메시지 변경
- 장바구니 에러 메시지 변경
> hotfix: 장바구니 에러 메시지 변경

- .github/workflows/script-prod.yml
> ci: 잘못된 스크립트 정보 수정

- .github/workflows/script-dev.yml
- .github/workflows/script-prod.yml
> ci: application-els.yml 파일 CI/CD 파이프라인에 추가

- README.md
- src/main/java/com/palpal/dealightbe/domain/member/application/MemberService.java
- src/main/java/com/palpal/dealightbe/domain/member/application/dto/request/MemberUpdateReq.java
- src/main/java/com/palpal/dealightbe/domain/member/application/dto/response/MemberUpdateRes.java
- src/main/java/com/palpal/dealightbe/domain/member/presentation/MemberController.java
- src/test/java/com/palpal/dealightbe/domain/member/application/MemberServiceTest.java
- src/test/java/com/palpal/dealightbe/domain/member/presentation/MemberControllerTest.java
어떤 변경 사항이 있나요?
- 멤버 프로필 수정 닉네임 중복검사
- 멤버 프로필 수정 닉네임 중복검사를 추가했습니다.
- 멤버 프로필 수정 닉네임 중복검사를 반영해 테스트 코드를 수정했습니다.
> hotfix: 멤버 프로필 수정 닉네임 중복검사

- src/main/java/com/palpal/dealightbe/domain/member/application/MemberService.java
- src/main/java/com/palpal/dealightbe/domain/member/domain/Member.java
- close: https://github.com/Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-BE/issues/296
어떤 변경 사항이 있나요?
- Member 인덱스 적용 및 updateProfile 로직을 수정했습니다.
- Member의 providerId에 인덱스 적용
- updateProfile시, 닉네임 중복검사 하지 않도록 수정
> Member 인덱스 적용 및 updateProfile 수정

- src/main/java/com/palpal/dealightbe/domain/item/domain/ItemRepositoryImpl.java
- src/main/resources/data.sql
- close: #300 
어떤 변경 사항이 있나요?
- 상품 목록 조회 기능 커버링 인덱스 적용
- 조건별, 업체별 상품 목록 조회 기능에 커버링 인덱스를 적용하여 성능을 개선했습니다.
> 상품 목록 조회 기능 커버링 인덱스 적용

- build.gradle
- src/docs/asciidoc/Cart.adoc
- src/main/java/com/palpal/dealightbe/config/BucketConfig.java
- src/main/java/com/palpal/dealightbe/domain/cart/application/CartService.java
- src/main/java/com/palpal/dealightbe/global/error/ErrorCode.java
- src/main/java/com/palpal/dealightbe/global/error/GlobalExceptionHandler.java
- src/main/java/com/palpal/dealightbe/global/error/exception/ExcessiveRequestException.java
- src/main/resources/data.sql
- src/test/java/com/palpal/dealightbe/domain/cart/presentation/CartControllerTest.java
> 장바구니 담기, 수정 기능 요청 횟수 제한

- .github/workflows/script-prod.yml
> ci: script-prod.yml에 도커 컴포즈 test 컨테이너 올리는 명령 추가
